### ISSUE TITLE
Is the rasterazing done with anti-aliasing ?

### ISSUE THREAD

**Issue by ngirard** [nickbrowne/nsvg#3]
Hi, I'm involved in the [IconPie](https://github.com/GarkGarcia/icon-pie) project, which uses your crate for SVG rasterizing.

We would like to know, is the rasterizing is performed with anti-aliasing ?

Cheers !

**Comment by nickbrowne** [comment]
Hi there, 

Yes, nanosvg (the C library that performs the rasterisation) does perform anti-aliasing: https://github.com/memononen/nanosvg/blob/master/src/nanosvgrast.h#L891

From what I understand, the nanosvg rasteriser is heavily based on the one used by stb_truetype, you can find out a bit more about how it works here if you are interested: https://nothings.org/gamedev/rasterize/

**Comment by ngirard** [comment]
@nickbrowne, thanks for your fast and thorough reply ! I'll close this issue, but you might want to mention it in your own README.

Cheers !

**Comment by nickbrowne** [comment]
I've just updated the readme to be a bit more accurate about the actual capabilities of the version of NanoSVG that nsvg is using, as the readme was originally written with a very old version in mind.

The example has also been updated to demonstrate more of the features supported.

I've also mentioned that the rasteriser will render with anti-aliasing. Hope this helps with IconPie.

**Comment by ngirard** [comment]
Great, thanks !
